# Generated by Django 5.1.2 on 2025-02-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscribe',
            name='max_count_qrs',
            field=models.SmallIntegerField(null=True),
        ),
    ]
