# Generated by Django 5.1.2 on 2025-02-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_usersubscribe_max_count_qrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscribe',
            name='cvv_code',
            field=models.SmallIntegerField(null=True),
        ),
    ]
