# Generated by Django 5.1.6 on 2025-02-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0003_usersubscribe_cvv_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscribe',
            name='date_expired',
            field=models.CharField(max_length=20),
        ),
    ]
