# Generated by Django 5.1.6 on 2025-03-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0004_alter_usersubscribe_date_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscribe',
            name='date_expired_subscribe',
            field=models.DateField(null=True),
        ),
    ]
