# Generated by Django 5.1.6 on 2025-03-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0005_usersubscribe_date_expired_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscribe',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
    ]
