# Generated by Django 5.1.6 on 2025-03-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0006_usersubscribe_is_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscribe',
            name='is_working',
            field=models.BooleanField(default=True),
        ),
    ]
