# Generated by Django 5.1.3 on 2025-01-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code_number',
            name='user_id',
            field=models.SmallIntegerField(default=10, max_length=10),
            preserve_default=False,
        ),
    ]
