# Generated by Django 5.1.3 on 2025-01-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration1', '0003_alter_code_number_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_number',
            name='number',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='code_number',
            name='user_id',
            field=models.SmallIntegerField(),
        ),
    ]
