# Generated by Django 5.1.3 on 2025-01-17 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration1', '0004_alter_code_number_number_alter_code_number_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code_number',
            name='email',
        ),
    ]
