# Generated by Django 5.1.3 on 2025-01-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration1', '0005_remove_code_number_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='code_number',
            name='if_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='code_number',
            name='if_login',
            field=models.BooleanField(default=False),
        ),
    ]
