# Generated by Django 5.1.3 on 2025-01-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration1', '0006_code_number_if_email_code_number_if_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code_number',
            name='if_email',
        ),
        migrations.RemoveField(
            model_name='code_number',
            name='if_login',
        ),
    ]
