# Generated by Django 5.1.2 on 2025-01-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerate_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qr_codes',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='qr_codes',
            name='image',
            field=models.ImageField(null=True, upload_to='media/images/qrcodes'),
        ),
        migrations.AddField(
            model_name='qr_codes',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qr_codes',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
