# Generated by Django 5.1.6 on 2025-02-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerate_app', '0002_rename_user_qr_codes_user_id_qr_codes_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr_codes',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
