# Generated by Django 5.1.6 on 2025-02-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerate_app', '0003_qr_codes_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qr_codes',
            old_name='user_id',
            new_name='user',
        ),
    ]
