# Generated by Django 5.1.6 on 2025-02-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerate_app', '0004_rename_user_id_qr_codes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_codes',
            name='date_created',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='qr_codes',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
