# Generated by Django 5.1.6 on 2025-03-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerate_app', '0005_alter_qr_codes_date_created_alter_qr_codes_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect_QR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField()),
            ],
        ),
    ]
