# Generated by Django 5.1.6 on 2025-03-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerate_app', '0006_redirect_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect_qr',
            name='qrcode',
            field=models.CharField(max_length=255),
        ),
    ]
