# Generated by Django 5.1.6 on 2025-03-02 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerate_app', '0007_alter_redirect_qr_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect_qr',
            name='qr_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='qrgenerate_app.qr_codes'),
        ),
    ]
