# Generated by Django 5.1.6 on 2025-03-02 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerate_app', '0008_redirect_qr_qr_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redirect_qr',
            old_name='qr_id',
            new_name='qr',
        ),
    ]
