# Generated by Django 5.1.6 on 2025-03-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerate_app', '0009_rename_qr_id_redirect_qr_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr_codes',
            name='is_working',
            field=models.BooleanField(default=True),
        ),
    ]
